### ISSUE TITLE
Home Page Weather Display Card enhancement

### ISSUE THREAD

**Issue by ak8057** [R0Y15/WeatherNow#100]
I could enhance the weather display card, making it more appealing
Could  you please assign me this task under Hacktoberfest2024

**Comment by R0Y15** [comment]
Sure, Please Go Ahead

**Comment by MrSwapnilRahate** [comment]
If you need any help... I'm ready to help

**Comment by R0Y15** [comment]
@ak8057 @MrSwapnilRahate would you guys like to collaborate together and then work on the issue?

if no, @ak8057 please provide the updates from your side.

**Comment by ak8057** [comment]
@MrSwapnilRahate i appreciate your interest to help me with the enhancement, but i guess i could handle this by myself, and i would suggest,  you could raise new issue and could work on adding many other feature to the website, Thanku
