### ISSUE TITLE
Including a line-graph that gives the hourly forecast of the given input city. 

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#11]
refer this picture
![image](https://github.com/R0Y15/WeatherNow/assets/66421958/50890d68-2566-4fb4-8c66-39fc5f9e53f5)

**Comment by Devrishi-Dutta** [comment]
can i work on this issue?

**Comment by harsh-p05** [comment]
Hey @R0Y15 
I would like to work on the same can I try and pls provide me some details for the graph

**Comment by R0Y15** [comment]
> Hey @R0Y15 I would like to work on the same can I try and pls provide me some details for the graph

you can refer to the picture provided above for details that are required for the graph, the project gets weather details from "openweathermap"

**Comment by Devrishi-Dutta** [comment]
@R0Y15 can I make a pr now?

https://github.com/R0Y15/WeatherNow/assets/97834009/5496abf9-846f-48f3-b33a-5eee6c9dc929

**Comment by R0Y15** [comment]
> @R0Y15 can I make a pr now?
> 
>  WeatherNow.-.Google.Chrome.2023-10-05.22-16-16.mp4

that is pretty cool.. but ig your are not updated with the latest merge. please pull once and make sure that there are no conflicts, once done go for a pr, I'll try to merge it asap.
