### ISSUE TITLE
Adding similar footer to About Us Page for consistency

### ISSUE THREAD

**Issue by TeekshaHarish** [R0Y15/WeatherNow#115]
This content "WeatherNow is a weather application that displays the weather of any city.
© Roy™" on About Us page should be as a footer at the bottom with full width and dark background like in the home page to maintain consistency. 
About Us:
![image](https://github.com/user-attachments/assets/4a786902-307b-429c-a37a-6b0c9e7491dc)

Home page Footer:
![image](https://github.com/user-attachments/assets/c0e54e33-fee2-4796-8849-3a1a0b319cc8)

**Comment by R0Y15** [comment]
Hi @TeekshaHarish, Please follow the home screen's style pattern for the other pages. This is just a small suggestion, if you wish to propose a fresh design please proceed.
