### ISSUE TITLE
ui enhancement of profile cards.

### ISSUE THREAD

**Issue by irshadsiddi** [R0Y15/WeatherNow#127]
hey @R0Y15,

want to add a glassy effect and add a gradient glow to the profile cards in the contributors page. this will look nice.
![Screenshot from 2024-10-24 20-05-27](https://github.com/user-attachments/assets/f8ccba03-d689-43f8-8329-6bf71f6c8c24)
here is an example.
![Screenshot from 2024-10-24 20-11-40](https://github.com/user-attachments/assets/ae76e212-bb28-4bfc-99dd-a5d7d70f4c5d)

please assign this task to me under hacktoberfest.

**Comment by R0Y15** [comment]
Hi, @irshadsiddi the existing page looks quiet subtle, but however I'd love to see your idea. Please proceed but keep in mind that there will be chances of getting the PR merged.

All the best.
