### ISSUE TITLE
Adding Search Suggestion for Cities

### ISSUE THREAD

**Issue by atinder-harika** [R0Y15/WeatherNow#131]
Hey there,

As of right this moment the search box is basically just type and search but I can help add search suggestion using a free api for cities around the world. This will not only help enhance user experience but also make the process of entering cities with difficult names much easier. Later on we can explore smart search where even if the user enters incorrect spelling we display the closest possible city. 

@R0Y15 Kindly assign me this issue with the tag hacktoberfest so I can get started.

Thanks

**Comment by R0Y15** [comment]
Good Luck @atinder-harika

**Comment by atinder-harika** [comment]
@R0Y15 I have opened pull request #134. Kindly review and add it before October ends.
