### ISSUE TITLE
Add a loader that is shown before the page is completely loaded.

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#14]

**Comment by IrfanSalim** [comment]
I would like to work on this, please assign

**Comment by devdeep2003** [comment]
I would like to be assigned on this , please consider my request.

**Comment by R0Y15** [comment]
@IrfanSalim @devdeep2003 guys I've assigned it to both of you, I know both of your contributions would be much appreciable than an individual's work.. Happy hacking :)
