### ISSUE TITLE
Addition of Future Weather predictions tab/cards

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#2]

**Comment by dipandhali2021** [comment]
hi @R0Y15 , i want to work on this issue .Assign me this issue.

**Comment by R0Y15** [comment]
> hi @R0Y15 , i want to work on this issue .Assign me this issue.

Sure, go ahead :)

**Comment by sampath-kumaramd** [comment]
Hey again,  can you assign this one as well. I will work both of this issues.

**Comment by R0Y15** [comment]
Sure
