### ISSUE TITLE
Adding a bundler

### ISSUE THREAD

**Issue by Cstrp** [R0Y15/WeatherNow#25]
@R0Y15 Maybe this project should be "modular"? What I mean by that is that most web applications hosted on the web use builders like webpack | gulp | parsel etc. I could add a webpack and add a development server (instead of the same vscode extension).  

> Note: This is not necessary.

**Comment by R0Y15** [comment]
does that anyhow enhance the website? If yes lets do it!

**Comment by Cstrp** [comment]
> does that anyhow enhance the website? If yes lets do it!

In my opinion, this will improve the experience for developers. For a website, since the project is small, it will not add performance by reducing the size of the files, however, if you plan to integrate some heavy ideas (images, videos), this can help, but it will also be far from easy)

**Comment by R0Y15** [comment]
> > does that anyhow enhance the website? If yes lets do it!
> 
> In my opinion, this will improve the experience for developers. For a website, since the project is small, it will not add performance by reducing the size of the files, however, if you plan to integrate some heavy ideas (images, videos), this can help, but it will also be far from easy)

well then I suggest lets not take things far and make it hard for beginners to contribute to this project since this project was started to let beginner contributors start with GIT, If you still want to make such contributions please do checkout my other repo "The-Wild" and add your valuable ideas to it.
