### ISSUE TITLE
Addition of past weather history tab/card/section 

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#3]

**Comment by CoderRedwing** [comment]
can i work on it

**Comment by R0Y15** [comment]
> can i work on it

sure, Good Luck ;)

**Comment by sampath-kumaramd** [comment]
hey, do you wanna create a card or tab or section on home page

**Comment by R0Y15** [comment]
> hey, do you wanna create a card or tab or section on home page

a card section that shows the past weather history next to the search bar would be great ig, what do u suggest?

**Comment by sampath-kumaramd** [comment]
sure, can you assign this issue to me, and will see how it look like?

**Comment by R0Y15** [comment]
> sure, can you assign this issue to me, and will see how it look like?

cool, lets do it. All the best & happy hacking :)
