### ISSUE TITLE
Adding a background to the site

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#33]
expected is adding a soothing background. here are some optional requirements:
- cursor responsive background
- background image that changes every time a new city a searched and some image related to the city is displayed 
- gradient background that keeps changing 

note: these are just suggestions and this repo is open for contributors to add their creativity

**Comment by Bimme2audrey** [comment]
Hey, For the gradient background, should it be images?

**Comment by R0Y15** [comment]
> Hey, For the gradient background, should it be images?

it can be but it would be more better if that keeps changing its colors (like gif's to be precise)

**Comment by Bimme2audrey** [comment]
Alright, I'll love to contribute

**Comment by R0Y15** [comment]
Cool.. assigning you the issue
