### ISSUE TITLE
Fix the Go Button

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#56]
Either of the changes is required

- Make the arrow appear and hide the text on hover
- Make the arrow translate-x when hover (For this make sure to keep the arrow just beside the Go text)

**Comment by TusharGupta-Developer** [comment]
@R0Y15 Hi, I would like to work on this issue. Could you please assign it to me? Thanks!

**Comment by R0Y15** [comment]
Good Luck

**Comment by anant-jain01** [comment]
@R0Y15 can you assign me the issue as well under the hacktoberfest tag?
