### ISSUE TITLE
Addition of weather icons that suite the weather condition of the searched location

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#6]

**Comment by avishkaindula** [comment]
I would like to work on this issue

**Comment by Ejay02** [comment]
cool, pls assign it to me

**Comment by Ejay02** [comment]
also, I'll be taking out the empty result border box that's visible before the API call is made.

**Comment by Ejay02** [comment]
Made PR for these updates.
![image](https://github.com/R0Y15/WeatherNow/assets/66236069/965bcf95-00ac-4690-99d0-d2f9d1dafde2)
![image](https://github.com/R0Y15/WeatherNow/assets/66236069/37d1f150-82db-4444-bf94-903baa0050ed)

**Comment by R0Y15** [comment]
> I would like to work on this issue

If you still wish to add more to the project, please let me know so that I can assign this to u as well

**Comment by Ejay02** [comment]
ok thanks, ill check it out and let you know.
