### ISSUE TITLE
Change Profile photo shape

### ISSUE THREAD

**Issue by Deekshashakyawal** [R0Y15/WeatherNow#60]
I want to change the contributors photo shape from square to circle as it would look much better.

![Screenshot 2024-10-10 181033](https://github.com/user-attachments/assets/a5e3e5c7-8eae-4530-959c-a50e856e1322)
 
Please assign me this issue under Hacktoberfest

**Comment by R0Y15** [comment]
Sure Go ahead @Deekshashakyawal
