### ISSUE TITLE
The "Go" Button

### ISSUE THREAD

**Issue by anant-jain01** [R0Y15/WeatherNow#63]
When I hover on the go button ideally the "Go"  written should go or the "arrow" should not be there. Please assign me the issue under hacktoberfest tag.

**Comment by R0Y15** [comment]
Good Luck, Excited to see the Updates

**Comment by anant-jain01** [comment]
Please check my pull request. If you choose to accept please use the appropriate hacktoberfest tag

**Comment by HarshitaJaiswal5** [comment]
@R0Y15 can you assign me this issue?

**Comment by R0Y15** [comment]
@HarshitaJaiswal5 Sorry for the delay, are you still interested in working on this project?

**Comment by anant-jain01** [comment]
@R0Y15 this issue has been fixed.
Kindly recheck..

**Comment by R0Y15** [comment]
> @R0Y15 this issue has been fixed. Kindly recheck..

ohh my bad. Sorry for the confusion
