### ISSUE TITLE
Issues related to color scheme of the buttons and "Default" menu list

### ISSUE THREAD

**Issue by anant-jain01** [R0Y15/WeatherNow#64]
The color scheme of the buttons should be the same in order to enhance the website's consistency. Also some minor issues are their which once fixed will enhance the overall visual appeal of the website.
The nav bar at the top also has the same issues.
Please assign me the issue under the hacktoberfest tag.

**Comment by R0Y15** [comment]
I'm excited to see how your idea turns out. Good Luck :)

**Comment by anant-jain01** [comment]
check my pull request #70
