### ISSUE TITLE
Change the Github Icon

### ISSUE THREAD

**Issue by Deekshashakyawal** [R0Y15/WeatherNow#68]
I want to change the Github icon in contributors page

![Screenshot 2024-10-10 181033](https://github.com/user-attachments/assets/eb449716-ff65-43a0-b507-a62755324418)

Please assign me this under Hacktoberfest

**Comment by R0Y15** [comment]
Hi @Deekshashakyawal, any updates regarding this issue?

**Comment by Deekshashakyawal** [comment]
The contributors page looks like , so should I add a github icon because currently the github profile link is embedded to the block itself instead of any separate github icon. 

![Screenshot 2024-10-18 180700](https://github.com/user-attachments/assets/082c0931-6d16-4bff-98e3-e879c1aef1a5)

**Comment by R0Y15** [comment]
No the current updates are very much satisfied.
