### ISSUE TITLE
Fix the Graph Content

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#77]
Modify the graph element such that weather for some of the recent days are displayed.

**Comment by Hriishikeshh** [comment]
hey i would like to work on this assign it to me if suited @R0Y15

**Comment by R0Y15** [comment]
@Hriishikeshh Sorry for the delay, are you still interested in working on this issue?

**Comment by R0Y15** [comment]
@Hriishikeshh assigining this to you, please proceed.

**Comment by Hriishikeshh** [comment]
thank you for assigning can you elaborate a bit in where the graph element is to be worked out

**Comment by R0Y15** [comment]
Please imporve the UI of the graph, and rather than displaying such dense information, I'd be really great if summarized data is shown.

**Comment by Hriishikeshh** [comment]
hey the openmapapi is asking for subscription can you provide it by any means possible?

**Comment by Hriishikeshh** [comment]
i have summarized the data can you raise another issue so that it counts as another pr from my side for the hacktoberfest

**Comment by R0Y15** [comment]
Hi, @Hriishikeshh You can certainly raise an issue yourself as well. Please proceed raising one, I'll mark it as hecktoberfest
