### ISSUE TITLE
add contact page and review

### ISSUE THREAD

**Issue by Sahoobarsharani** [R0Y15/WeatherNow#88]
please assign this to me gssoc ext and hacktoberfest2024

**Comment by R0Y15** [comment]
Sure, Make sure to follow the color/theme of the project

**Comment by R0Y15** [comment]
@Sahoobarsharani any updates on this issue?

**Comment by Sahoobarsharani** [comment]
yes i am in the process of resolving the issue

**Comment by R0Y15** [comment]
> yes i am in the process of resolving the issue

alright
