### ISSUE TITLE
PlaceHolder Not working with "Enter" key

### ISSUE THREAD

**Issue by R0Y15** [R0Y15/WeatherNow#9]

**Comment by Cstrp** [comment]
I can fix it. Do you mean that pressing the enter key does not poison the prompt?

**Comment by R0Y15** [comment]
> I can fix it. Do you mean that pressing the enter key does not poison the prompt?

yes

**Comment by Cstrp** [comment]
Okay, now is work [PR](https://github.com/R0Y15/WeatherNow/pull/10#issue-1927984148)
