### ISSUE TITLE
feat: Suntracker

### ISSUE THREAD

**Issue by AdityaSinha2305** [R0Y15/WeatherNow#91]
I want to try to add a sun tracker feature.
Can you assign me this under hacktoberfest?

**Comment by R0Y15** [comment]
@AdityaSinha2305  sure, please go ahead. also make sure to mention the issue number in the pr inorder to keep track of the PR

**Comment by AdityaSinha2305** [comment]
Okay. I have also created a pr related to sunrise and sunset timing #90 please do check and merge if everything works fine.
