### ISSUE TITLE
Visit count track .

### ISSUE THREAD

**Issue by melan-variya** [R0Y15/WeatherNow#92]
i would like to add visit count on top of the page 
like this 
![Screenshot 2024-10-15 144233](https://github.com/user-attachments/assets/58ae8d33-fe50-4b83-85fd-23759f1415e3)
can you assign me this task by labeling hacktoberfest

**Comment by R0Y15** [comment]
@melan-variya Sure lets see how it turns out, however the color pattern of this functionality doesn't pretty match with the project theme. please make sure to keep the color in mind.
