### ISSUE TITLE
change background according to the weather

### ISSUE THREAD

**Issue by nidhi752** [R0Y15/WeatherNow#98]
This feature dynamically changes the background of the web page based on the current weather conditions. By integrating weather data, the background adapts in real-time to reflect the environment, such as sunny, rainy, or snowy conditions, creating a more immersive user experience. This enhancement adds a personalized touch to the application, making it visually engaging and responsive to users.
Please assign this to me under hackoctoberfest

**Comment by R0Y15** [comment]
@nidhi752 Glad to hear that you wish to contribute to my project. I'm excited to see the potential changes you wish to make in this project; however, I also want you to focus on the background not getting zoomed in when a user searches for a city.
all the best

**Comment by R0Y15** [comment]
@nidhi752 can you please provide me updates regarding this issue?

**Comment by nidhi752** [comment]
@R0Y15  hi, yes
I have been trying since yesterday but i am unable to run this locally. I mean it's not fetching data from the api. The site is working, but i am unable to figure out why it isn't fetching

**Comment by R0Y15** [comment]
Alright, lemmi know if you need any help anywhere.

**Comment by nidhi752** [comment]
Hi, yes I do need help. It's just not fetching locally.

**Comment by R0Y15** [comment]
what exactly do you see. please share some ss or anything related to the issue that you see on your screen.

**Comment by atinder-harika** [comment]
@R0Y15 If the assignee cannot resolve the issue I would be glad to work on this

**Comment by R0Y15** [comment]
Hi @atinder-harika I've assigned this issue to you, please proceed

Best wishes
